project_id = "gjthxhfnyigvihywibca"

[functions.submit-event]
verify_jwt = false

[functions.verify-event]
verify_jwt = false

[functions.manage-event]
verify_jwt = false

[functions.renew-event]
verify_jwt = false

[functions.daily-maintenance]
verify_jwt = false

[functions.feeds]
verify_jwt = false
